# -*- coding: utf-8 -*-
"""e-commerce sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLYPQFaFqU_W_lrZXoyeLxyvkC8Y_AAw
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

!pip install openpyxl
import zipfile

try:
    with zipfile.ZipFile("archive.zip", "r") as z:
        # List all files in the zip archive
        print(z.namelist())
except zipfile.BadZipFile:
    print("Error: archive.zip is not a valid zip file.")

# If the zip file contains an Excel file, extract it and then read it with pandas
# For example, if your zip file contains a file named 'data.xlsx', you would do the following:
with zipfile.ZipFile("archive.zip", "r") as z:
    z.extract("Superstore_USA.xlsx")
dataset = pd.read_excel("Superstore_USA.xlsx", engine='openpyxl')

dataset

dataset.head(2)

dataset.shape

dataset.isnull().sum()

dataset.info()

dataset["Order year"] = dataset['Order Date'].dt.year

dataset['Product Base Margin'].fillna(dataset['Product Base Margin'].mean(),inplace=True)

plt.figure(figsize=(6,4))
sns.barplot(x="Product Category",y="Product Base Margin",data=dataset,estimator='sum')
plt.show()

dataset['State or Province'].value_counts()[:5]

plt.figure(figsize=(6,4))
sns.barplot(x="Product Category",y="Profit",data=dataset,estimator='sum')
plt.show()

dataset['Order year'].value_counts()

plt.figure(figsize=(5,3))
sns.countplot(x="Order year",data=dataset)
plt.show()

"""***SHIP MODE***"""

dataset['Ship Mode'].value_counts()

x = dataset['Ship Mode'].value_counts().index
y=dataset['Ship Mode'].value_counts().values

plt.figure(figsize=(5,4))
plt.pie(y,labels=x,startangle = 60,autopct="%0.2f%%")
plt.legend(loc=2)
plt.title("Ship Mode")
plt.show()

plt.figure(figsize=(5,4))
sns.countplot(x="Ship Mode",data=dataset,hue="Product Category")
plt.title("Count of Ship Mode")
plt.show()

"""***CUSTOMER SEGMENT***"""

plt.figure(figsize=(6,4))
sns.countplot(x="Customer Segment",data=dataset)
plt.show()

"""***PRODUCT CATEGORY****"""

plt.figure(figsize=(5,3))
sns.countplot(x="Product Category",data=dataset)
plt.show()

plt.figure(figsize=(10,6))
sns.countplot(x="Product Category",data=dataset[dataset["Product Category"]=="Office Supplies"],hue="Product Sub-Category")
plt.show()

"""***ORDER PRIORITY***"""

dataset['Order Priority'].value_counts()

dataset['Order Priority'].unique()

dataset['Order Priority'] = dataset["Order Priority"].replace("Critical ","Critical")

dataset['Order Priority'].value_counts()

plt.figure(figsize=(5,3))
sns.countplot(x="Order Priority",data=dataset)
plt.title("Count of order priority")
plt.savefig("Count of order priority.jpg")
plt.show()















